### ISSUE TITLE
Remove unnecessary `defaultObj` in `07_parameters.test.js`

### ISSUE THREAD

**Issue by callahad** [kentcdodds/es6-workshop#10]
https://github.com/kentcdodds/es6-workshop/blob/91fa5fa1c01e82fbf91b7b2f6b86c02f2fabc9f5/test-final/07_parameters.test.js#L109 has:

```
const defaultObj = {
  name: 'Aaron',
  age: 35,
  favoriteBand: 'Queen'
};

function myFunction({name = 'Aaron', age = 35, favoriteBand = 'Queen'} = defaultObj) {
  expect(name).to.exist;
  expect(age).to.exist;
  expect(favoriteBand).to.exist;
}

myFunction();
```

But `defaultObj` is actually redundant! If you just set it to `{}`, it still works. As best as I can wrap my head around it:
1. Default parameter replacement: `myFunction()` &rarr; `myFunction({})`
2. Destructuring: `name = {}.name; ...` all of which are `undefined`
3. Default parameters, again! `name = name === undefined ? 'Aaron' : name; ...` which effectively rebuilds `defaultObj`.

This is insane. WebAssembly can't come soon enough. :)

**Comment by kentcdodds** [comment]
Definitely true! Mind filing a PR?

**Comment by callahad** [comment]
It's on my TODO list. Currently 100% focused on finishing my own workshop
up ;)

**Comment by kentcdodds** [comment]
Looks like this was done. Thanks again :)
