### ISSUE TITLE
Help add extra credit tests and more!

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/es6-workshop#15]
I could use some help coming up with ideas for extra credit tests!

I recorded a video about how to do this:

[![es6-extra-credit-small](https://cloud.githubusercontent.com/assets/1500684/21432598/82d4fbdc-c829-11e6-8b17-b0c69c2b6b7d.png)](https://youtu.be/CSVOPw_5OT0)

Please also check the [Contributing guidelines](https://github.com/kentcdodds/es6-workshop/blob/master/CONTRIBUTING.md). Thanks for your help!

**Comment by Khaledgarbaya** [comment]
Hi @kentcdodds  probably I should create a separate issue, 
but seems that when I execute `yarn run setup` the value of `process.versions.node` will be `5.x.x` which is my system node version, but it should be v6 which installed through nvm.
I executed `npm run setup` and it is working fine.

**Comment by kentcdodds** [comment]
Hi @Khaledgarbaya,
Sure, things _might_ work alright with v5, but they're only guaranteed to work with v6. So I'd recommend you upgrade :)

**Comment by GizmoMKD-zz** [comment]
i think it's useful to add additional test like this one:

```javascript
const ORANGES = 7;
// it's important to note the nature of block scoping
{ 
	const ORANGES = 20;
	console.log(ORANGES);
}
console.log(ORANGES);
```

@kentcdodds what do you think?

**Comment by kentcdodds** [comment]
Thanks @GizmoMKD! We do have several tests for `let` and `const` that demonstrate this property: https://github.com/kentcdodds/es6-workshop/blob/master/templates/01_block-scoping.test.js

But I suppose they could be improved. Feel free to file a pull request!

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this for now. Still happy to accept PRs though!
