### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/es6-workshop#16]
Now that we have Node v6, we can use Proxies which is pretty legit. Let's make an example of this! [Some examples here](https://github.com/lukehoban/es6features#proxies)

**Comment by Khaledgarbaya** [comment]
Hi @kentcdodds,
Sounds like an interesting addition to your stack. Good job on the workshop content btw
I have few ideas 

- Simple example to log a property using `handler.get`
- Restricting read or write using `handler.get` and `handler.set`
- Validation properties like name, age birthdate etc...
- Building a class with private members etc, probably sum up all of the above

If you have more example or feedback please let me know.
If everything goes well I might open a pull request by the next week.

Best,
Khaled

**Comment by kentcdodds** [comment]
All those ideas sound great! I was thinking about it and came up with several similar use cases. I also created this little gem:

```javascript
const array = new Proxy([], {
  get(obj, prop) {
    if (prop === 'last') {
      return function last(fromLast = 0) {
        return obj[obj.length - fromLast - 1]
      }
    }
    return Reflect.get(obj, prop)
  }
})
array.push(1, 2, 3, 4, 5, 6)
console.assert(array.last() === 6)
console.assert(array.last(1) === 5)
console.assert(array.last(4) === 2)
```

Pretty neat stuff :)

**Comment by Khaledgarbaya** [comment]
Even better I came up with this example, a python like array 

```js
let array = new Proxy([], {
    get: function (receiver, index) {
      if (index in receiver) {
        return receiver[index]
      }
      const i = parseInt(index)
      if (!isNaN(i) && i < 0 && Math.abs(i) <= receiver.length) {
        return receiver[receiver.length + i]
      }
    }
  })
  
  array.push('firstItem', 'secondToLasItem', 'lastItem')
  
  console.log(array[0]) // outputs: 'firstItem'
  console.log(array[-1])// outputs: 'lastItem'
  console.log(array[-2])// outputs: 'secondToLasItem'
```

**Comment by kentcdodds** [comment]
Nice!
