### ISSUE TITLE
Should we have a prepush hook to run tests before pushing?

### ISSUE THREAD

**Issue by alayek** [kentcdodds/es6-workshop#40]
Something like the `"precommit"` script in `package.json`

```json
"prepush": "yarn setup"
```

Would this be a desired feature, to locally run the tests and lint before pushing? 

A use-case I can think of is to not have to wait till Travis gets back to the contributor that there is a minor lint violation.

**Comment by kentcdodds** [comment]
Actually, we already do have this :) But it's disabled by default (to make contributing easier): Enable it with this: https://github.com/kentcdodds/es6-workshop/blob/master/CONTRIBUTING.md#opt-into-git-hooks
