### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by nesaulov** [kentcdodds/es6-workshop#41]
I was running my first test on the first exercise and got a syntax error:
````
$ yarn test:changed
yarn test:changed v0.19.1
$ npm run test --silent -- --onlyChanged
 FAIL  exercises/01_block-scoping.test.js
  ● Test suite failed to run

    SyntaxError: Unexpected token {

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at process._tickCallback (node.js:369:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.729s
Ran all test suites related to changed files.
error Command failed with exit code 1.
````

The file itself definetely has no syntax errors, i can attach it if it helps.
Thanks!

**Comment by nesaulov** [comment]
Woops, seems like issue was caused by iTerm, native Mac terminal doesn't throw errors.

**Comment by kentcdodds** [comment]
Glad you got it worked out. The real problem was that you were using the wrong version of node. Make sure that you're using Node v6 as indicated in the instructions! Good luck!

**Comment by alayek** [comment]
@kentcdodds do you think we should add an `.nvmrc` and clearly provide the `"engines"` entry with Node latest LTS (v6.9.4)?

**Comment by kentcdodds** [comment]
Sure, couldn't hurt. We do have the verify script as part of setup, so people should be made aware of they set things up according to the instructions...
