### ISSUE TITLE
No option to run tests in "only changed" mode

### ISSUE THREAD

**Issue by aaronang** [kentcdodds/es6-workshop#46]
When running `yarn run test:watch`, there is no option to run in "only changed" mode, i.e. no `o` option. This makes me wonder why Jest decided to remove this option in the interactive dialog; the option can still be passed as an option to Jest CLI. 

Anyway, the ["How To Run Tests"](https://github.com/kentcdodds/es6-workshop#how-to-run-tests) needs to be updated.

Thanks a lot for this great workshop 😄

EDIT: I think Jest runs in "only changed" mode by default, i.e. no need to press `o` anymore.

**Comment by kentcdodds** [comment]
> EDIT: I think Jest runs in "only changed" mode by default, i.e. no need to press o anymore.

Correct, if you hit `a` (to change to run all mode), then it will show you the `o` option as a mode to switch back to:

<img width="682" alt="screen shot 2017-03-10 at 5 45 57 am" src="https://cloud.githubusercontent.com/assets/1500684/23795858/f57518d0-0554-11e7-97b6-b5e4b17fe5f8.png">

I'm glad it was helpful!
