### ISSUE TITLE
One question about 01_block-scoping quizz

### ISSUE THREAD

**Issue by Tivcrmn** [kentcdodds/es6-workshop#54]
I run `yarn start` and go into the interactive mode.
When I run this function. I think it should throw an error about the reference due to let and const, but it did not.

![image](https://user-images.githubusercontent.com/22848627/43197623-4d59bcac-903e-11e8-8a55-e59dba7f34f9.png)

![image](https://user-images.githubusercontent.com/22848627/43197700-889ad6a2-903e-11e8-98ed-acaa8af92dc6.png)

Is this something wrong with the settings in this project about babel?

**Comment by kentcdodds** [comment]
Huh, that's odd. I'm not sure I have time to look into this. Sorry 🤔😔

**Comment by Tivcrmn** [comment]
Haha, it is so weird. I move this file into ~/Desktop. it works and throw an error...
![image](https://user-images.githubusercontent.com/22848627/43357273-815b9ff0-92b1-11e8-8e1f-344c49d9767c.png)
