### ISSUE TITLE
Migrate to AVA

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/es6-workshop#9]
Just because I think it's simpler, faster, and I want to encourage people to use it :-)

**Comment by callahad** [comment]
I'm working on a similar workshop myself, and I'm not certain raw AVA is a great fit.

I'd absolutely prefer AVA for a real project, where the developers are expected to know and learn the testing framework, understand Promises, etc. But for a project designed to _teach_ those things... this repo's BDD and `expect` style reads much more clearly to me.

**Comment by callahad** [comment]
Also, AVA + Babel is hell on npm v2, which still ships with the current Node LTS (v4.x). Seeing ~7s startup delays on a moderately spec'd laptop with a good SSD.

Upgrading to Node v5.10 gives me ~1s startups on the same hardware. :(

**Comment by kentcdodds** [comment]
Good point. I'll stick with mocha for the reasons you described. Looking forward to startup improvements on the AVA side and EOL on npm@2!!!
